name: ros2-talker-listener-fabolhak
version: '0.1'
summary: ROS2 Talker/Listener Example
description: |
  This example launches a ROS2 talker and listener.

confinement: devmode
base: core18

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: dashing
    colcon-rosdistro: crydashingstal
    colcon-source-space: demo_nodes_cpp
    build-packages: [make, gcc, g++]
    stage-packages: [ros-dashing-ros2launch]

apps:
  run:
    command: opt/ros/dashing/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py


architectures:
  - build-on: amd64
    run-on: [amd64, armhf, arm64]